prestige:
    1:
        prefix: "&8[&6¤&f1st&6¤&8]"
        price: 6000000000
    2:
        prefix: "&8[&6¤&f2nd&6¤&8]"
        price: 7000000000
    3:
        prefix: "&8[&6¤&f3rd&6¤&8]"
        price: 8000000000
    4:
        prefix: "&8[&6¤&f4th&6¤&8]"
        price: 9000000000
    5:
        prefix: "&8[&6¤&f5th&6¤&8]"
        price: 10000000000
    6:
        prefix: "&8[&6¤&f6th&6¤&8]"
        price: 11000000000
    7:
        prefix: "&8[&6¤&f7th&6¤&8]"
        price: 12000000000
    8:
        prefix: "&8[&6¤&f8th&6¤&8]"
        price: 13000000000
    9:
        prefix: "&8[&6¤&f9th&6¤&8]"
        price: 14000000000
    10:
        prefix: "&8[&6¤&f10th&6¤&8]"
        price: 15000000000
